#!/bin/bash -
#title           : dropbox-sync
#description     : Defines behaviour of starting script
#author		     : Keisuke Suzuki
#usage		     : ./dropbox-sync
#notes           : Shell utilities functions are derived from
#                  @ralish https://github.com/ralish/bash-script-template
#===============================================================================
source utils

D_ROOT=$HOME/Dropbox
PATH1=$HOME/Documents
PATH2=$HOME/Pictures
D_PATH1=$D_ROOT/Documents
D_PATH2=$D_ROOT/Pictures


run() {
    while inotifywait -r -e modify,create,delete,move \
        "$D_ROOT" "$PATH1" "$PATH2"; do
        ## Unison does not recognize touching a file
        unison -batch "$PATH1" "$D_PATH1" -logfile $HOME/.unision.log
        unison -batch "$PATH2" "$D_PATH2" -logfile $HOME/.unision.log
    done
}


parse_params() {
    local param
    while [[ $# -gt 0 ]]; do
        param="$1"
        shift
        case $param in
            -h | --help)
                script_usage
                exit 0
                ;;
            -r | --run)
                run "$@"
                ;;
            *)
                script_exit "Invalid parameter was provided: $param" 1
                ;;
        esac
    done
}

# DESC: Main control flow
# ARGS: $@ (optional): Arguments provided to the script
# OUTS: None
main() {
    trap script_trap_err ERR
    trap script_trap_exit EXIT

    script_init "$@"
    parse_params "$@"
    colour_init
    #lock_init system
}

main "$@"
